# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{noratext}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["KOJIMA Satoshi"]
  s.date = %q{2010-07-14}
  s.description = %q{noratext is a simple (and rather stupid) lexer and parser generator for loosly markuped text.  }
  s.email = %q{skoji@mac.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/noratext.rb",
     "lib/noratext/lexer.rb",
     "lib/noratext/parser.rb",
     "lib/noratext/parser_element.rb",
     "lib/noratext/processor.rb",
     "lib/noratext/xmly_lexer.rb",
     "spec/noratext_lexer_spec.rb",
     "spec/noratext_parser_spec.rb",
     "spec/noratext_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/ydml_grammer_definition.rb"
  ]
  s.homepage = %q{http://github.com/skoji/noratext}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{noratext: simple lexer/parser generator for markuped text}
  s.test_files = [
    "spec/noratext_lexer_spec.rb",
     "spec/noratext_parser_spec.rb",
     "spec/noratext_spec.rb",
     "spec/spec_helper.rb",
     "spec/ydml_grammer_definition.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

